echo 'Digite o nome do arquivo:'
read -p "-> " file
sed -i -e 's/Â/A/g' ${file}
sed -i -e 's/Ã/A/g' ${file}
sed -i -e 's/Á/A/g' ${file}
sed -i -e 's/À/A/g' ${file}
sed -i -e 's/Ä/A/g' ${file}
sed -i -e 's/â/a/g' ${file}
sed -i -e 's/ã/a/g' ${file}
sed -i -e 's/á/a/g' ${file}
sed -i -e 's/à/a/g' ${file}
sed -i -e 's/ä/a/g' ${file}
sed -i -e 's/Ê/E/g' ${file}
sed -i -e 's/Ẽ/E/g' ${file}
sed -i -e 's/É/E/g' ${file}
sed -i -e 's/È/E/g' ${file}
sed -i -e 's/Ë/E/g' ${file}
sed -i -e 's/ê/e/g' ${file}
sed -i -e 's/ẽ/e/g' ${file}
sed -i -e 's/é/e/g' ${file}
sed -i -e 's/è/e/g' ${file}
sed -i -e 's/ë/e/g' ${file}
sed -i -e 's/Î/I/g' ${file}
sed -i -e 's/Ĩ/I/g' ${file}
sed -i -e 's/Í/I/g' ${file}
sed -i -e 's/Ì/I/g' ${file}
sed -i -e 's/Ï/I/g' ${file}
sed -i -e 's/î/i/g' ${file}
sed -i -e 's/ĩ/i/g' ${file}
sed -i -e 's/í/i/g' ${file}
sed -i -e 's/ì/i/g' ${file}
sed -i -e 's/ï/i/g' ${file}
sed -i -e 's/Ô/O/g' ${file}
sed -i -e 's/Õ/O/g' ${file}
sed -i -e 's/Ó/O/g' ${file}
sed -i -e 's/Ò/O/g' ${file}
sed -i -e 's/Ö/O/g' ${file}
sed -i -e 's/ô/o/g' ${file}
sed -i -e 's/õ/o/g' ${file}
sed -i -e 's/ó/o/g' ${file}
sed -i -e 's/ò/o/g' ${file}
sed -i -e 's/ö/o/g' ${file}
sed -i -e 's/Û/U/g' ${file}
sed -i -e 's/Ũ/U/g' ${file}
sed -i -e 's/Ú/U/g' ${file}
sed -i -e 's/Ù/U/g' ${file}
sed -i -e 's/Ü/U/g' ${file}
sed -i -e 's/û/u/g' ${file}
sed -i -e 's/ũ/u/g' ${file}
sed -i -e 's/ú/u/g' ${file}
sed -i -e 's/ù/u/g' ${file}
sed -i -e 's/ü/u/g' ${file}
sed -i -e 's/Ç/C/g' ${file}
sed -i -e 's/ç/c/g' ${file}
sed -i -e 's/º/o/g' ${file}
sed -i -e 's/ª/a/g' ${file}
sed -i -e 's/Ñ/N/g' ${file}
sed -i -e 's/ñ/n/g' ${file}
