name: Makefile CI

on:
	push:
		branches: [ "master" ]
	pull_request:
		branches: [ "master" ]

jobs:
	build:

		runs-on: ubuntu-latest

		steps:
		- uses: actions/checkout@v3

		- name: Build Small_Compiler
		run: cd codes/Compilers/Small_Compiler && make

		- name: Test Small_Compiler
		run: cd build && ./parser Sample_00
